name: CI/CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
# GitHubPagesへのデプロイを許可
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Setup Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.11.0
      - name: Install Dependency
        run: pnpm install
      - name: Build Storybook
        run: pnpm run build:ui
      - name: Upload Storybook
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./.storybook
      - name: Deploy Storybook
        uses: actions/deploy-pages@v2
      - name: Lint Prettier
        run: pnpm run lint:format
      - name: Lint Stylelint
        run: pnpm run lint:style
      - name: Lint Eslint
        run: pnpm run lint:script
      - name: Test Storybook
        run: pnpm run test:ui.ci
      - name: Test Vitest
        run: pnpm run test:ut
      - name: Test Playwright
        run: pnpm run test:it
